export enum ExpenseCategory {
  GASOLINA = 'GASOLINA',
  VENENOS_QUIMICOS = 'VENENOS_QUIMICOS',
  HERRAMIENTAS_EQUIPOS = 'HERRAMIENTAS_EQUIPOS',
  TRANSPORTE = 'TRANSPORTE',
  PUBLICIDAD = 'PUBLICIDAD',
  OTROS = 'OTROS',
}
